
"""import sqlite3
conn=sqlite3.connect('test.db')
print("opened database successfully")
conn.execute('''create table companies
(ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
ADDRESS CHAR(50),
SALARY REAL)''')
"""


"""conn.execute("INSERT INTO COMPANIES(ID,NAME,ADDRESS,SALARY) VALUES(1,'DANISH','INDIA',100000.00)")
conn.execute("INSERT INTO COMPANIES(ID,NAME,ADDRESS,SALARY) VALUES(2,'SHIN','INDIA',100000.00)")
cursor=conn.execute("SELECT ID,NAME,ADDRESS,SALARY from companies")
for row in cursor:
    print("ID=",row[0])
    print("NAME=", row[1])
    print("ADDRESS=", row[2])
    print("SALARY=",row[3]),"\n""""


conn.execute("UPDATE COMPANIES set SALARY=200000 WHERE ID=1")
conn.commit()



print("table created successfully")
conn.close(
import sqlite3
conn=sqlite3.connect('test.db')
print("opened database successfully")

conn.execute("INSERT INTO BOOKS(BOOK_ID,LOCATION,GENRE_ID) VALUES(2049,'DELHI',456)")
conn.execute("INSERT INTO TITLES(TITLE_ID,TITLE_NAME,ISBN,PUBLISHER_ID,PUBLISHER_YEAR) VALUES(123,'BHAGWAT GEETA','MSM6170',456789,768)")
conn.execute("INSERT INTO PUBLISHERS(PUBLISHER_ID,NAME,STREET ADDRESS,SUITE NUMBER ,ZIP CODE ID) VALUES(34567,BALWANT RAWAT,'NEERUVA',0UIO9,ACD123)")
conn.execute("INSERT INTO AUTHORTITLES(AUTHORS_ID,TITLE_ID) VALUES(56784,98764)")
conn.execute("INSERT INTO AUTHORS(AUTHOR_ID,FIRST_NAME,LAST_NAME) VALUES(1,'DANISH','GUPTA')")

print("Table created Successfully")
conn.close()

import sqlite3
conn=sqlite3.connect('sed.db')
print("opened database successfully")


conn.execute('''CREATE TABLE BOOK2(BOOK_ID INT PRIMARY KEY NOT NULL,LOCATION TEXT NOT NULL,GENRE_ID TEXT NOT NULL)''')
conn.execute('''CREATE TABLE TITLE2(TITLE_ID INT PRIMARY KEY  NOT NULL,TITLE_NAME CHAR(20) NOT NULL,ISBN INT NOT NULL,PUBLISHER_ID NOT NULL)''')
conn.execute('''CREATE TABLE PUBLISHER2(PUBLISHER_ID INT NOT NULL,NAME TEXT NOT NULL,STREET_ADDRESS CHAR(20),SUITE_NUMBER INT  NOT NULL,ZIP_CODE_ID INT NOT NULL)''')
conn.execute('''CREATE TABLE AUTHORTITLE2(AUTHORS_ID INT NOT NULL,TITLE_ID INT NOT NULL)''')
conn.execute('''CREATE TABLE AUTHOR2(AUTHOR_ID INT PRIMARY KEY NOT NULL,FIRST_NAME CHAR(20) NOT NULL,LAST_NAME CHAR(20) NOT NULL)''')
print("Table created Succefully")

import sqlite3
conn=sqlite3.connect('test.db')
print("opened database successfully")

conn.execute("INSERT INTO BOOKS(BOOK_ID,LOCATION,GENRE_ID) VALUES(2049,'DELHI',456)")
conn.execute("INSERT INTO TITLES(TITLE_ID,TITLE_NAME,ISBN,PUBLISHER_ID) VALUES(123,'BHAGWAT GEETA','MSM6170',456789)")
conn.execute("INSERT INTO PUBLISHERS(PUBLISHER_ID,NAME,STREET ADDRESS,SUITE NUMBER ,ZIP CODE ID) VALUES(34567,BALWANT RAWAT,'NEERUVA',0UIO9,ACD123)")
conn.execute("INSERT INTO AUTHORTITLES(AUTHORS_ID,TITLE_ID) VALUES(56784,98764)")
conn.execute("INSERT INTO AUTHORS(AUTHOR_ID,FIRST_NAME,LAST_NAME) VALUES(1,'DANISH','GUPTA')")

print("Table created Successfully")
conn.close()






