#q.no.1
import sqlite3
conn=sqlite3.connect('sell.db')
print("opened database successfully")


conn.execute('''CREATE TABLE BOOK2(BOOK_ID INT PRIMARY KEY NOT NULL,LOCATION TEXT NOT NULL,GENRE_ID TEXT NOT NULL)''')
conn.execute('''CREATE TABLE TITLE2(TITLE_ID INT PRIMARY KEY  NOT NULL,TITLE_NAME CHAR(20) NOT NULL,ISBN INT NOT NULL)''')
conn.execute('''CREATE TABLE PUBLISHER2(PUBLISHER_ID INT NOT NULL,NAME TEXT NOT NULL,STREET_ADDRESS CHAR(20),SUITE_NUMBER INT  NOT NULL,ZIP_CODE_ID INT NOT NULL)''')
conn.execute('''CREATE TABLE AUTHORTITLE2(AUTHORS_ID INT NOT NULL,TITLE_ID INT NOT NULL)''')
conn.execute('''CREATE TABLE AUTHOR2(AUTHOR_ID INT PRIMARY KEY NOT NULL,FIRST_NAME CHAR(20) NOT NULL,LAST_NAME CHAR(20) NOT NULL)''')
print("Table created Succefully")

#q.no.2
conn.execute("INSERT INTO BOOK2(BOOK2_ID,LOCATION,GENRE_ID) VALUES(2049,'DELHI',456)")
conn.execute("INSERT INTO TITLE2(TITLE2_ID,TITLE_NAME,ISBN) VALUES(123,'BHAGWAT GEETA','MSM6170')")
conn.execute("INSERT INTO PUBLISHER2(PUBLISHER2_ID,NAME,STREET_ADDRESS,SUITE_NUMBER ,ZIP_CODE_ID) VALUES(34567,'BALWANT RAWAT','NEERUVA',12345,5698)")
conn.execute("INSERT INTO AUTHORTITLE2(AUTHORS2_ID,TITLE_ID) VALUES(56784,98764)")
conn.execute("INSERT INTO AUTHOR2(AUTHOR2_ID,FIRST_NAME,LAST_NAME) VALUES(1,'DANISH','GUPTA')")
conn.commit()

#q.no.3
a=conn.execute("SELECT BOOK2_ID,TITLE2_ID,LOCATION,GENRE FROM BOOK2")
for b in a:
    print("BOOK2_ ID:",b[0])
    print("TITLE2_ID:",b[1])
    print("location:",b[2])
    print("GENRE:",b[3])
    conn.execute("UPDATE BOOK SET LOCATION='INDIA' WHERE BOOK_ID=1234")
    conn.commit
a=conn.execute("SELECT BOOK2_ID,TITLE2_ID,LOCATION,GENRE FROM BOOK2")
for d in a:
    print("BOOK2_ ID:",d[0])
    print("TITLE2_ID:",d[1])
    print("location:",d[2])
    print("GENRE:",d[3])
    conn.commit
conn.close()